
case "$1" in
    "workspace-1") echo "1" | xsel -i -b && xdotool key super+1 ;;
    "workspace-2") echo "2" | xsel -i -b && xdotool key super+2 ;;
    "workspace-3") echo "3" | xsel -i -b && xdotool key super+3 ;;
    "workspace-4") echo "4" | xsel -i -b && xdotool key super+4 ;;
    "workspace-5") echo "5" | xsel -i -b && xdotool key super+5 ;;
    "workspace-6") echo "6" | xsel -i -b && xdotool key super+6 ;;
    "workspace-7") echo "7" | xsel -i -b && xdotool key super+7 ;;
    "workspace-8") echo "8" | xsel -i -b && xdotool key super+8 ;;
    "workspace-9") echo "9" | xsel -i -b && xdotool key super+9 ;;
    "workspace-10") echo "10" | xsel -i -b && xdotool key super+0 ;;
    "send-workspace-1") xdotool key super+shift+1 ;;
    "send-workspace-2") xdotool key super+shift+2 ;;
    "send-workspace-3") xdotool key super+shift+3 ;;
    "send-workspace-4") xdotool key super+shift+4 ;;
    "send-workspace-5") xdotool key super+shift+5 ;;
    "send-workspace-6") xdotool key super+shift+6 ;;
    "send-workspace-7") xdotool key super+shift+7 ;;
    "send-workspace-8") xdotool key super+shift+8 ;;
    "send-workspace-9") xdotool key super+shift+9 ;;
    "send-workspace-10") xdotool key super+shift+0 ;;
    "close-window") xdotool key super+shift+c ;;
    "split-window") xdotool key super+shift+return ;;
    "fullscreen") notify-send "Fullscreen" "Fullscreen toggle not yet implemented" ;;
    "toggle-float") xdotool key super+shift+space ;;
    "focus-left") xdotool key super+h ;;
    "focus-right") xdotool key super+l ;;
    "focus-up") xdotool key super+k ;;
    "focus-down") xdotool key super+j ;;
    "move-left") xdotool key super+shift+h ;;
    "move-right") xdotool key super+shift+l ;;
    "move-up") xdotool key super+shift+k ;;
    "move-down") xdotool key super+shift+j ;;
    "layout-stack") xdotool key super+shift+s ;;
    "layout-tab") xdotool key super+shift+t ;;
    "layout-toggle") xdotool key super+space ;;
    "quit-xmonad") xdotool key super+shift+q ;;
    *) echo "Unknown command: $1" ;;
esac
