{ inputs, config, pkgs, lib, ... }:

let
  # System username - defined here as it's hardware/location specific
  # This is the username created by the GLFOS installer
  systemUsername = "zitchaden";
in
{
  # Export system username as a special argument for other modules
  _module.args.systemUsername = systemUsername;
  # NVIDIA Graphics Configuration - Hardware Specific
  # TODO: move autogenerated shims by the great GLFOS installer into a separate folder, stuff like environment type is hardware agnostic respective to x86_64 machines (the only GLF prerequisite)
  glf.nvidia_config = {
    enable = true;
    laptop = false;
    # NVIDIA Corporation GA102 [GeForce RTX 3080] (rev a1)
    nvidiaBusId = "PCI:1:0:0";
  };

  # User Account - Generated by GLFOS installer
  # This includes the user account and password setup
  users.users.${systemUsername} = {
    isNormalUser = true;
    description = systemUsername;
    extraGroups = [ "networkmanager" "wheel" "scanner" "lp" "disk" "input" "render" "video" ];
  };

  # Bootloader Configuration - Hardware Specific
  # GRUB configuration for this specific system
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "nodev";
  boot.loader.grub.efiSupport = true;
  boot.loader.grub.useOSProber = true;
  boot.loader.grub.efiInstallAsRemovable = true;

  # Networking - Hardware Specific
  # Hostname and network configuration for this system
  networking.hostName = "cogNito"; # Define your hostname.
  networking.networkmanager.enable = true;

  # Time Zone - Location Specific (not hardware specific, but system specific)
  # This could be different for different physical locations
  time.timeZone = "Europe/London";

  # Keyboard Layout - Hardware/Region Specific
  # Different keyboards or regions may need different layouts
  services.xserver.xkb = {
    layout = "us";
    variant = "";
  };

  # Internationalization - Region Specific
  # This is tied to the device's usage location and language preferences
  i18n.defaultLocale = "en_GB.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_GB.UTF-8";
    LC_IDENTIFICATION = "en_GB.UTF-8";
    LC_MEASUREMENT = "en_GB.UTF-8";
    LC_MONETARY = "en_GB.UTF-8";
    LC_NAME = "en_GB.UTF-8";
    LC_NUMERIC = "en_GB.UTF-8";
    LC_PAPER = "en_GB.UTF-8";
    LC_TELEPHONE = "en_GB.UTF-8";
    LC_TIME = "en_GB.UTF-8";
  };
}
